- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    region: "us-east-1"
    instance_type: "t2.micro"
    image: "ami-07626b842f1104fe6"
    security_group: "sg-0ab84156357937300"
    keypair: "R.N_keypair"
    instance_name: "TestAnsible"
    domain: "ensys.jp"
    count_tags: Name='foo count'
    instance_count: 1

  tasks:
    - name: Launch instance
      ec2_instance :
        name: "{{ instance_name }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group }}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        tags:
          Domain: "{{ domain }}"
        wait: true
      register: ec2

    - name: Add new instance to host group
      local_action: add_host name={{ ec2.instances[0].public_ip_address }} groups='launched'

    - name: Wait for SSH to come up
      local_action: wait_for host={{ ec2.instances[0].public_ip_address }} port=22 delay=60 timeout=320 state='started'

- name: Setup Utsusemi instance
  hosts: launched
  gather_facts: False
  become: yes
  become_user: root
  vars:
    cognito_region: 'us-east-1'
    cognito_userpoolID: 'us-east-1_HeTmsbb6v'
    cognito_apliclientID: '11gts94au5vs64mluogodsn0s9'
    cognito_idpoolID: 'us-east-1:55f4013e-5fce-4c0a-a9cc-e588a2b6b30c'

    postgres_userID: 'utsusemiuser'
    postgres_password: 'ad307483'

    mail_from: 'no-reply@utsusemi.cloud'
    mail_to: 'unicia127@gmail.com'
    mail_smtp_server: 'email-smtp.us-east-1.amazonaws.com'
    mail_smtp_userID: 'AKIAI7LZXPO2CI2MAA2Q'
    mail_smtp_password: 'AsEAShL//yyFbCdmrwvtcRayMhPvNsnLVwtGZdSYnH5j'

  tasks:
    - name: (1)Create /etc/utsusemi/webapps/.cognito
      template:
        src: /etc/git/ansible/cognito.j2
        dest: /etc/utsusemi/webapps/.cognito
        owner: tomcat
        group: tomcat
        mode: 0700

    - name:  (2)Create /etc/utsusemi/webapps/.postgres
      template:
        src: /etc/git/ansible/postgres.j2
        dest: /etc/utsusemi/webapps/.postgres
        owner: tomcat
        group: tomcat
        mode: 0700

    - name:  (3)Create /etc/utsusemi/webapps/.signup
      template:
        src: /etc/git/ansible/signup.j2
        dest: /etc/utsusemi/webapps/.signup
        owner: tomcat
        group: tomcat
        mode: 0700
