- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  connection: local

  vars:
    keypair: "R.N_keypair"
    instance_type: "t2.micro"
    instance_tags: Name='TestAnsible2',Domain='ensys.jp'
    instance_name: TestAnsibles
    count_tags: Name='foo count'
    security_group: "sg-003ffde6972513793"
    image: "ami-03d822ebef35ac5e0"
    region: "us-east-1"
    instance_count: 1

  tasks:
    - name: Launch instance
      ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ security_group }}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        wait: true
      register: ec2

    - name: Add new instance to host group
      local_action: add_host name={{ item.public_ip }} groups='launched'
      with_items: '{{ ec2.instances }}'

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state='started'
      with_items: '{{ ec2.instances }}'

    - name: Write IP Addresses to Log File
      local_action: shell cd /etc/ansible; echo {{ item.public_ip}} >> createdEC2
      with_items: '{{ ec2.instances }}'

- name: Setup Utsusemi instance
  hosts: launched
  gather_facts: False
  become: yes
  become_user: root
  vars:
    region: 'us-east-1'
    userpoolID: 'us-east-1_HeTmsbb6v'
    apliclientID: '11gts94au5vs64mluogodsn0s9'
    idpoolID: 'us-east-1:55f4013e-5fce-4c0a-a9cc-e588a2b6b30c'

  tasks:
    - template:
        src: /etc/ansible/cognito.j2
        dest: /etc/utsusemi/webapps/.cognito
        owner: tomcat
        group: tomcat
        mode: 0700

